### ISSUE TITLE
Package missing from Yarn

### ISSUE THREAD

**Issue by tylerrowsell** [arcetros/scrape-recipe-schema#24]
When I go to pull in the package on yarn it fails.
https://yarnpkg.com/package/scrape-schema-recipe

**Comment by arcetros** [comment]
Hey @tylerrowsell , it looks like the package name you were trying to install was incorrect. The correct package name is 'scrape-recipe-schema', and you can find it on Yarn at this link: https://yarnpkg.com/package/scrape-recipe-schema. I hope this helps!
